# Generated by Django 2.2.3 on 2019-10-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20191016_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, help_text='* shipping to whom or who is it for', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='nickname',
            field=models.CharField(blank=True, help_text='* your preferred name', max_length=120, null=True),
        ),
    ]
